version: '3'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./node:/app
    image: sakhih/super-app-node-exercise
    depends_on:
      - php
      - db

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
    image: sakhih/super-app-php-exercise
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
